QuickChick/QuickChick

src/Decidability.v
Makes it possible to do the following:
```Coq
> Compute (1=1 /\ 2=2)?.
= true : bool
> Compute (1=1 /\ 2=3)?.
= false : bool
> Compute (1=1 \/ 2=3)?.
= true : bool
> Compute (~1=1 \/ 2=3)?.
= false : bool
```
=> More `Dec` instances.

.travis.yml
For now, we test only the build and install of QuickChick, and the
multifile-mutation example.
=> Continuous testing with Coq 8.6.

src/GenHigh.v
=> Optimize proofs in GenHigh

examples/stlc/verif.v
=> Fix stlc example: Use PeanoNat instead of deprecated NPeano

src/Instances.v
Fixes #51.
Shall I also add this to `coq.8.6`?
=> Avoid looping instance resolution

_CoqProject, src/Show.v, src/ShowFacts.v
Also define read for strings and prove roundtrip. Fixes #62.
=> Make Show properly escape strings

src/Test.v
The termination checker can see through nested fixpoints!
=> Refactor localMin

DocumentationCheck.v, QuickChickInterface.v, src/ExtractionQC.v, src/Show.v
These were previously axioms, and it was not possible to show things in Gallina.
=> Implement show for basic types in Gallina

.travis.yml, opam, src/depDriver.ml, src/driver.ml4, src/genericLib.ml, src/genericLib.mli, src/quickChick.ml4, src/simplDriver.ml, src/tactic_quickchick.ml4, src/weightmap.ml4
This is in preparation, the Coq PR hasn't been merged yet.
=> Adapt to Coq's PR #7797 (removal of reference).

src/dune
This has no effect in the regular build, but allows composition with
Coq master.
=> [build] Add Dune support.

quickChickTool/quickChickTool.ml
Overlay to merge when indicated upstream.
=> [coq] Adapt to coq/coq#8914

opam, src/Test.v
@liyishuai Merge once you've added simple-io to coq-extra-dev and fixed CI to point to it.
Fixes #129
=> Upgrade coq-simple-io dependency

src/Mutation.v, src/Test.v
I just fast-forwarded simple-io's `dev` to the current `master` which is getting stabilized. This is the associated changes.
=> Upgrade simple-io

opam, src/Mutation.v, src/Test.v
=> Upgrade simple-io (8.9 branch)

src/genericLib.ml
=> Fix w.r.t. coq/coq#9476.

src/genericLib.ml
=> Adapt to coq/coq#8817 (SProp)

src/genericLib.ml, src/quickChick.mlg
To be merged only once coq/coq#9678 is.
=> Adapt to changes in Coq's printers API

src/arbitrarySized.ml, src/arbitrarySizedST.ml, src/checkerSizedST.ml, src/depDriver.ml, src/driver.mlg, src/dune, src/genericLib.ml, src/quickChick.mlg, src/setLib.ml, src/simplDriver.ml, src/sizeCorr.ml, src/sizeMon.ml, src/sizeSMon.ml, src/sizeUtils.ml, src/sized.ml, src/sizedProofs.ml, src/unify.ml, src/weightmap.mlg
This provides a warning-free OCaml build except for warning 8.
Warning 8 is a problem tho as usually is a pretty serious one.
=> [warnings] Pass on removing OCaml warnings.

src/CoArbitrary.v, src/DependentClasses.v, src/GenLow.v
=> +new proofs in CoArbitrary, GenLow and DependentClasses

.gitignore, Makefile.coq.local, src/depDriver.ml, src/genericLib.ml
This closes #143 and makes QuickChick compliant with
https://github.com/coq/coq/pull/9605
Can be merged without too many problems I think.
=> [coq] Remove some more warnings, disable pervasive warning 8

src/quickChick.mlg
To merge when upstream PR is merged.
=> [coq] Adapt to coq/coq#9895

.travis.yml, src/depDriver.ml, src/driver.mlg, src/genericLib.ml, src/genericLib.mli, src/simplDriver.ml
=> adapt to coq #10215

.travis.yml, src/quickChick.mlg
=> Fix w.r.t. coq/coq#10406.

src/quickChick.mlg
Should be backward compatible, hopefully.
=> Adapt to coq/coq#10427.

CHANGELOG.md, src/quickChick.mlg, test/plugin/plugin.v
=> Touch mli file

src/tactic_quickchick.mlg
=> Fix w.r.t. coq/coq#11896.

src/quickChick.mlg, src/tactic_quickchick.mlg
=> Send test output to coqtop instead of stdout

src/ExtractionQC.v
=> Fix modn extraction (m %% 0 is m, not 0)

src/driver.mlg
=> Add QCDerive to disambiguate from Derive from other plugins

examples/RedBlack/testing.v, examples/RedBlack/verif.v, examples/ifc-basic/Rules.v, examples/sf/Equiv.v, examples/sf/Hoare.v, examples/sf/Imp.v, examples/sf/IndProp.v, examples/sf/Smallstep.v, examples/stlc/lambda.v, examples/stlc/verif.v, src/CoArbitrary.v, src/Test.v
Close #211 
FYI: this was a simple `sed 's/Omega/Lia/g'` and `sed 's/omega/lia/g'` plus one place where I removed `zify`.
=> omega -> lia

plugin/genericLib.ml
=> Adapt w.r.t. coq/coq#14148.

compat.pl, plugin/genericLib.ml
Follow up to #221 
Why did CI not complain?
=> Add compatibility shim for Classes.new_instance

plugin/dune, plugin/quickChick.mlg, quickChickTool/dune, quickChickTool/quickChickTool.ml
=> Capture build output in QuickChick command

.gitattributes, coq-quickchick.opam, quickchick.opam
=> opam: depends on cppo

plugin/quickChick.mlg.cppo, src/RoseTrees.v
=> More informative messages on unexpected failures

Makefile, src/ExtractionQC.v.cppo
=> ExtractionQC: Use Random.full_int with OCaml 4.13

.gitignore, Makefile, Makefile.coq.local, _CoqProject, plugin/META.coq-quickchick.in, src/QuickChick.v
To be merge when https://github.com/coq/coq/pull/15220 is.
=> adapt to coq/coq#15220

.circleci/config.yml, dune-project, plugin/dune, quickChickTool/dune, src/dune
=> dune: Fix package name to coq-quickchick

Makefile, examples/pyml/Makefile, plugin/quickChick.mlg.cppo, quickChickTool/quickChickTool.ml, test/mutation/mutation.sh
=> Add -use-ocamlfind flag to ocamlbuild

QuickChickInterface.v, src/Classes.v, src/CoArbitrary.v, src/Decidability.v, src/DependentClasses.v, src/GenHighImpl.v, src/GenHighInterface.v, src/GenLow.v, src/GenLowInterface.v, src/Instances.v, src/MutateCheck.v, src/Mutation.v, src/RandomQC.v, src/SemChecker.v, src/Sets.v, src/Show.v, src/Test.v, src/Typeclasses.v
Backwards compatible in theory.
=> Adapt w.r.t. coq/coq#16004.

src/RandomQC.v
Improves robustness in case of stronger (e)auto (see [coq/#16293](https://github.com/coq/coq/pull/16293)).
=> improved auto goal selection

CHANGELOG.md
=> Next release

plugin/tactic_quickchick.mlg.cppo
This should be backwards compatible.
=> Adapt w.r.t. coq/coq#16730.

.gitignore, examples/deriving-tests/function.v, plugin/unifyQC.ml.cppo
=> Explicit function application

examples/RedBlack/testing.v, examples/ifc-basic/DerivedGen.v, examples/ifc-basic/GenExec.v, examples/ifc-basic/Generation.v, examples/ifc-basic/Printing.v, tutorials/BasicUsage.v
Very small changes to prepare the removal of some deprecated files.
=> Adapt wrt to Coq/Coq#18164

src/Producer.v
Adapt to https://github.com/coq/coq/pull/18590
=> Adapt to https://github.com/coq/coq/pull/18590

plugin/quickChick.mlg.cppo
=> Generate truly unique temporary directories

.circleci/config.yml
=> ci: Ignore hacky upper bound on dune

.gitignore, Makefile, coq-quickchick.opam, dune-project, plugin/quickChick.mlg.cppo, plugin/quickChick.mli.cppo, plugin/tactic_quickchick.mlg.cppo
Not sure we want to allow opaque access through tactics.
=> (CHEATING) Adapt to coq/coq#18422 (indirect accessor handled through vernactypes)

src/CheckerProofs.v, src/EnumProofs.v, src/GenProofs.v
I couldn't test this PR because for some weird reason the Coq CI script doesn't work locally for simple-io. Assuming it works it is backwards compatible.
=> Adapt w.r.t. coq/coq#18940.

plugin/depDriver.ml.cppo
=> Drop support for Coq < 8.15

plugin/dune, plugin/unifyQC.mli, plugin/unifyQC.mli.cppo
To be merged synchronously with coq/coq#19075. Thanks in advance.
=> Adapt to Coq PR #19075: make CSet extensible

src/TacticsUtil.v.cppo
Adapt to https://github.com/coq/coq/pull/19310
This should be merged in sync with the upstream PR
=> Adapt to https://github.com/coq/coq/pull/19310

.circleci/config.yml, plugin/unifyQC.mli.cppo
=> ci: Coq 8.20

examples/other/dune, plugin/dune, scripts/dune, scripts/mk-mycppo, src/dune
Don't use shebangs, call sh explicitly
cc @MSoegtropIMC
=> Fix mycppo script for Windows

.gitignore, coq-quickchick.opam, coq-quickchick.opam.template, dune-project
per https://github.com/coq/opam/pull/3235#discussion_r1871862931
=> change dune idiom

examples/RedBlack/dune, examples/RedBlack/testing.v.cppo, examples/other/enumProofs.v, src/Classes.v, src/LazyList.v, src/TacticsUtil.v.cppo
Adapt to https://github.com/coq/coq/pull/19530
To be merged in sync with the upstream PR.
=> Adapt to https://github.com/coq/coq/pull/19530

doc/DocumentationCheck.v, examples/other/Reflection.v, examples/other/neg_example.v, plugin/genericLib.ml.cppo, sf-experiment/Basics.v, sf-experiment/Induction.v, sf-experiment/Lists.v, src/ExtractionQC.v.cppo, src/Producer.v, src/RoseTrees.v, src/Sets.v
Adapt to https://github.com/math-comp/math-comp/pull/1415
=> Adapt to https://github.com/math-comp/math-comp/pull/1415

src/ExtractionQC.v.cppo, test/dune, test/extraction.v
=> Inline extraction of constants from the OCaml stdlib
