QuickChick/QuickChick

- src/Classes.v
- src/Instances.v
- src/Test.v
- src/classes_old.v
- src/coqLib.ml
This file (from Coq stdlib) is deprecated, and it turns out that using
it triggers an extraction bug (the .ml file produced by Separate
Extraction does not match the .mli file).
We should still try to minimize and report the extraction bug, but from
QuickChick's point of view, this is an easy fix.
> Remove dependency on NPeano.

- .gitignore
- src/quickChick.ml4
- src/tactic_quickchick.ml4
This should be compatible with any Coq/OCaml combination. Soon, Coq
will use this stricter flag by default.
> Fix compilation of quickchick with OCaml's -strict-sequence on.

- src/Show.v
There is now a `=?` notation in `string_scope`, so we need to delimit some other scopes explicitly.
Although this does need to be merged to be compatible (and it's backwards compatible), I'm not sure if there are other things that need to be adapted, because I can't actually test all of QuickChick, because it doesn't seem to build with Coq master?  I get
```
$  make COQBIN="$HOME/Documents/repos/coq-string-eqb/bin/" -j100
make -f Makefile.coq
make[1]: Entering directory '/home/jgross/Documents/repos/QuickChick'
ocamlbuild -use-ocamlfind -pkg coq.lib -cflags -rectypes -tag thread quickChickTool/quickChickTool.byte
+ ocamlfind ocamldep -package coq.lib -modules quickChickTool/quickChickTool.ml > quickChickTool/quickChickTool.ml.depends
ocamlfind: Package `coq.lib' not found
Command exited …
```
> Adapt to https://github.com/coq/coq/pull/8063

- src/Tactics.v
This backward-compatible patch prepares QuickChick for
https://github.com/coq/coq/pull/7878
> Prepare for porting to lia

- _CoqProject
- scripts/quickchick
- scripts/quickchick-expectfailure
- src/Mutation.v
- src/QuickChick.v
- test/.gitignore
- test/Makefile
- test/mutation/mutation.sh
- test/mutation/mutation.v
The gist is: compile once, get all the mutants in the final executable. See comments in `src/Mutation.v`.
With this PR I also propose a simplification of `quickChickTool`.
The main nontrivial thing `quickChickTool` does that I would like to remove is the generation of `QuickChickTop.v`. Indeed, it is quite difficult to automate the following tasks correctly (currently very rigid assumptions are made about how the project is set up for this, and in `DeepWeb`/`dsss18/dw` they caused a lot of problems):
- mapping filepaths to logical paths in order to import properties found in `(*! QuickChick ... *)` comments;
- injecting `QuickChickTop.v` into the build system.
In fact, I don't think that work is worth automating in the first place: if users are willing to write `(*! QuickChick ... *)` …
> Simpler framework for mutation testing

- src/quickChick.ml4
In theory this should be backwards compatible, but I didn't test.
> Fix compilation for coq/coq#8601.

- src/sizeCorr.ml
The `Extraction` plugin is packed, thus its modules must be opened
with their full path.
This will become an error soon.
> [coq] Fix pack qualification for Extraction module.

- src/genSTCorrect.ml
- src/sizedProofs.ml
Opening of plugin modules must be properly scoped. Unfortunately I
missed a couple more of cases in #117.
Technical note, this works due to bug in `coq_makefile` [but usually
may fail later at linking], but it will stop working soon.
> [coq] Fix more incomplete open of packed plugin modules.

- src/DependentClasses.v
Change from premises `H1, H2, H2, H3` to `H1, H2, H3, H4`.
Adds compatibility with coq/coq#8820.
> Deduplicate premise name

- src/CoArbitrary.v
- src/Decidability.v
- src/Typeclasses.v
This option is soon going to be turned off by default. See
https://github.com/coq/coq#9270
This patch should be backward compatible. It wasn't 100% clear to me on which branch I base it, even after reading the contributing guide.
> Do not rely on `Refine Instance Mode`

- src/Classes.v
- src/DependentClasses.v
This is in preparation for coq/coq#9274.
Should be backward compatible but that remains to be tested.
> Make trivial instances explicit

- src/ShowFacts.v
I thought it's better to prove decimal_thousand and ascii_256 than to leave them Admitted.
> +ShowFacts proofs, less Coq warnings

- Makefile
- src/weightmap.mlg
This PR fixes a couple of issues forgotten or introduces in #158, in
particular we should not clean the `Makefile.coq.local` file, and we
forgot a warning in an `.mlg` [due to editing the wrong file].
> [coq_makefile] Some more fixes following #158

- Makefile
- quickChickTool/_tags
- quickChickTool/quickChickTool.ml
- quickChickTool/quickChickToolLexer.mll
Removes dependency on libraries coqlib (internal Coq library), str, and module `Option` (only since ocaml 4.08).
Fixes #103.
> Reduce dependencies of quickChickTool

- src/genericLib.ml
- src/genericLib.mli
- src/simplDriver.ml
- src/unify.ml
`Option` is only available since OCaml 4.08 (how did it go through CI?) and str is weird (like unix, but that's harder to avoid) so avoiding it is one less headache when you don't have a proper dependency resolver.
> plugin: Remove dependency on str and Option

- src/ExtractionQC.v
Getting ocaml’s `Fatal error: exception Division_by_zero` instead of `+++ Passed 10000 tests` was somewhat unexpected.
> fix div/mod extraction

- src/tactic_quickchick.mlg
Hi, Coq [PR#11141](https://github.com/coq/coq/pull/11141) simplifies the organization of options to printing functions (including `extern_constr`) thanks to labels.
This QuickQuick PR is to adapt to the Coq PR (an argument to remove in `extern_constr`). Since QuickChick is tested in the Coq Continuous Integration, it should be merged synchronously with the Coq PR (the assignee is @ejgallego). Thanks!
> Adapt to Coq PR11141

- src/driver.mlg
- src/weightmap.mlg
Hi, QuickChick is part of Coq CI and to keep it consistent with our tests, the attached change will have to be applied at the time [Coq PR#10932](https://github.com/coq/coq/pull/10832) is merged.
Coq PR#10932 adds an extra argument to the `CNotation` constructor and this PR is to adapt QuickChick `mlg` files to this change.
Note that the purpose of Coq PR#10932 is to fix attach formats to specific interpretations of notations. In particular, this fixes [Coq issue #6082](https://github.com/coq/coq/issues/6082).
> Adapting to Coq PR#10832 (extra scope argument to CNotation).

- src/ExtractionQC.v
- src/quickChick.mlg
No longer depend on an external file, which can break other people's workflow.
This is also a better fix than the [old one](https://github.com/QuickChick/QuickChick/commit/dadabe5971ed87d78c6653c5abe3d3a20a8f1c35) (the fix before the previous one) which crippled `int`.
See #193. I'm not sure this PR alone resolves the issue entirely given that the problem still exists on 1.2.0 which is what you will get on 8.10. What's a good way to backport bugfixes? Make a `v1.2.1`?
Also, ideally, QuickChick should not be the one changing extraction of standard data types, but that's going to take more time to figure out.
> Better fix for Decimal.int extraction

- src/GenHighImpl.v
- src/Instances.v
- src/Tactics.v
For real this time.
`git grep "\\<omega"` shows only occurrences in `sf-experiments` which is in a broken state anyway. (Note we also have a local `ssromega` tactic which is now defined in terms of `lia`).
> omega -> lia (continued)

- src/RandomQC.v
This should be backwards compatible and so may be merged now.
> Don't rely on setod rewrite forgetting arrow binder names (coq/coq#13882)

- plugin/depDriver.ml
- plugin/genericLib.ml
- plugin/quickChick.mlg
- plugin/tactic_quickchick.mlg
The `CApp` and `CAppExpl` constructors lose the part of their syntax which served to encode projections and this leads to some simplifications.
This has to be merged synchrounously with coq/coq#14598. Thanks in advance.
> Adapting to Coq PR #14598: adding an explicit constr_expr node for projections.

- .circleci/config.yml
- plugin/quickChick.mlg.cppo
The `run` command just prints the first argument, which is what we want for `QuickChick prop`, but not for `QuickChickWith arg prop`.
> plugin: Fix log message when calling QuickChickWith

- src/ExtractionQC.v.cppo
In particular Init.Nat.div (NOT Nat.div from importing Arith!)
led to QuickChick running in time quadratic to the number of test cases.
Init.Nat.div < roundTo < computeSize' < quickCheckWith
Closes #251
> Fix extraction of inefficient Nat arithmetic

- src/GenHighImpl.v
- src/Sets.v
This should be a backwards compatible fix for Coq PR #13969, making a rewrite go much faster as typeclass resolution no longer searches aimlessly.
> Fix for coq PR#13969

- plugin/quickChick.mlg.cppo
- Use "&&" instead of ";"
- Call test executable by its absolute path
Addresses #269 at least to the extent that `QuickChick` commands do work in Cygwin and CoqIDE.
> plugin: Add Windows compatibility

- quickChickTool/quickChickToolParser.mly
```
File "quickChickTool/quickChickToolParser.mly", line 50, characters 22-33:
Warning: when --strategy simplified is selected,
the error token may appear only at the end of a production
(and the semantic action must abort the parser).
This production will be ignored.
```
> quickChickTool: Fix warning

- plugin/quickChick.mlg.cppo
This PR fixes the last remaining issue in #269.
> Windows: Pass on environment when running quickchick native executable, so that PATH is correct

- plugin/tactic_quickchick.mlg.cppo
After some stronger invariant upstream, the name here has to match the
name used in `Declare ML Module` and `DECLARE PLUGIN`
Backwards compatible.
> [coq] Use findlib name in DECLARE PLUGIN

- examples/DependentTest.v
- examples/RedBlack/testing.v
- examples/RedBlack/verif.v
- examples/Tutorial.v
- examples/ifc-basic/DerivedGen.v
- examples/ifc-basic/Driver.v
- examples/ifc-basic/GenExec.v
- examples/ifc-basic/Generation.v
- examples/ifc-basic/Indist.v
- examples/ifc-basic/Printing.v
- examples/stlc/lambda.v
- examples/stlc/monad.v
The `examples` folder was forgotten in #291.
> Adapt examples w.r.t. coq/coq#16004.

- src/ExtractionQC.v.cppo
- src/Test.v
ExtractionQC.v.cppo had a bug that caused `withTime` to not work anymore. Removing the constructor fixes that.
The aim for the analysis output is that it will be used as JSON output, parentheses are added for that purpose.
> Updating Bug in Analysis Output.

- plugin/unifyQC.ml
This breaks async proofs and will probably break separation of parsing.
> Don't force references at linking time

- examples/Tutorial.v
Per #267, VSCoq places QuickChick output in a non-obvious location, so it appears as though `QuickChick` is a no-op unless you know exactly where to look.  While this could be documented in the README or some other top-level document, I think having it front-and-centre in the tutorial is optimal as I imagine that's the location where newcomers are most likely to trip over things.  (This was my situation this afternoon, for instance.)  I do concede that it breaks the flow of the tutorial a bit, though, so not opposed to the alternative.
> Tutorial: mention output location within VS Code's VSCoq plugin

- .circleci/config.yml
- Makefile
- dune-project
- plugin/driver.mlg
- plugin/genericLib.ml.cppo
- plugin/tactic_quickchick.mlg.cppo
- plugin/weightmap.mlg.cppo
- src/ExtractionQC.v.cppo
- src/GenLow.v
- src/Sets.v
Use `uncurry` instead of deprecated `prod_curry` (coq/coq#16920).
> Adapt to coq/coq#16920

- src/Instances.v
This should be backwards compatible.
The current master branch exploits a bug in the intropattern evaluation, where a split pattern is successfully applied to a higher-order hypothesis even though the dependent argument cannot be solved.
> Adapt w.r.t. coq/coq#17564.

- README.md
Ran into this while going through the artifact instructions at https://github.com/jwshi21/etna
> `etna:README.md`: fix `opam install . --deps-only`

- Makefile
`make documentation-check` doesn't cache the output of the `coqc` invocations and hence those invocations are re-run every time this target is run (unclear to me if this is intentional).
This also happens during `make install`, which means that non-installation related things are happening inside of opam during installation.
> Don't build documentation during install

- plugin/genericLib.ml.cppo
Adapt to https://github.com/coq/coq/pull/14928
> Adapt to coq/coq#14928

- Makefile
- examples/TacticExample.v
- examples/stlc/verif.v
- plugin/genericLib.ml.cppo
- plugin/genericLib.mli
- plugin/quickChick.mlg
- plugin/tactic_quickchick.mlg.cppo
- plugin/tactic_quickchick.mli
- src/ExtractionQC.v.cppo
Adds a tactic for Quickchecking the current proof goal in a naive fashion, using default generators for all variables and checking and filtering inputs against the hypotheses.
> Basic quickchick tactic for use during proofs

- plugin/genericLib.ml.cppo
This is the same fix as in https://github.com/QuickChick/QuickChick/pull/314 but applied on `master` (and I squashed the two commits that introduced changes). Please see that PR for more details.
> Fix for deriving DecOpt when index of inductive is from an inductive family

- examples/other/DependentTest.v
- plugin/arbitrarySized.ml
- plugin/arbitrarySizedST.ml
- plugin/arbitrarySizedST.mli
- plugin/genLib.ml
- plugin/genLib.mli
- plugin/weightmap.mlg.cppo
- plugin/weightmap.mli
- Use `thunkGen` when deriving generators (both Arbitrary and ArbitraryST) to avoid eager evaluation causing exponential overheads.
- Introduce thunked variants of oneof and frequency in genLib.
- Correctly use `size` as the weight of recursive calls.
> Defer evaluation of recursive generator calls when deriving generators

- plugin/quickChick.mlg.cppo
As noted in #267, VSCoq would completely ignore QuickChick's messages (and other similar information at "Info" level), hiding them in a hard-to-find buffer. This moves all printing to use `Feedback.msg_notice` instead of `Feedback.msg_info`, which sets QuickChick's messages at the same level as `Print foo` or `Show foo` commands.
> Move QuickChick's printing from info to notice

- examples/other/DependentTest.v
- plugin/arbitrarySizedST.ml
- plugin/genericLib.ml.cppo
- plugin/genericLib.mli
When deriving a constrained generator, QuickChick sometimes produces pattern matches of the form:
```
match x with
| <pattern> => ...
| _ -> ret None
```
When the `pattern` belongs to a singleton constructor, the "catch-all" branch should be elided.
This is done via a (very simple) checker in the definition of `match_inp` in ArbitrarySizedST.ml where we check the number of constructors in the type the root constructor of the `pattern` belongs to. 
This PR fixes this checker to take into account that some of the arguments to the root constructor can be types, while still making the branch exhaustive.
Also adds a relevant test in `DependentTest.v`.
> Fix derive singleton ctrs

- plugin/dune
> Re-enable warning 9 (Missing fields in a record pattern)

- plugin/driver.mlg
QuickChick and Equations cannot be required/imported in the same file in older versions of Coq (<= 8.18) since they both define a `Derive` vernacular using the same id "Derive".
This PR changes it to "QuickChickDerive" to avoid clashes with other plugins defining a `Derive` vernacular.
Related to https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Anomaly.3A.20bad.20vernac.20extend
> Change Derive vernacular identifier

- plugin/arbitrarySized.ml
- plugin/arbitrarySized.mli
- plugin/driver.mlg
- plugin/enumSized.ml
- plugin/genericLib.ml.cppo
- plugin/genericLib.mli
- plugin/quickChick.mlg.cppo
- plugin/simplDriver.ml
- plugin/simplDriver.mli
- plugin/sized.ml
- plugin/sized.mli
- src/EnumProofs.v
- src/GenProofs.v
- test/derive.v
- test/dune
This pull request adds partial support for deriving instances of mutually inductive types. Only limited to simple typeclasses.
The supported typeclasses are:
- GenSized
- EnumSized
- Shrink
- Arbitrary
- Show
- Sized
To give a simple example, with this pull request, the following now works:
```coq
Require Import QuickChick.QuickChick.
Inductive a :=
| A1 : a
| A2 : b -> a
with b :=
| B1 : b
| B2 : a -> b.
Derive Show for a.
Eval compute in
(show (A2 (B2 A1))).
(* "A2 (B2 A1)" *)
```
> Add support for deriving simple instances for mutually inductive types.
